name: flutterapp
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  pie_chart: ^5.4.0
  camera: ^0.11.0+2
  cupertino_icons: ^1.0.6
  smooth_page_indicator: ^1.1.0
  http: ^0.13.5
  flutter_local_notifications: ^12.0.0
  socket_io_client: ^2.0.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/smile.jpg
    - assets/mic.jpg
    - assets/cry_dark.jpg
    - assets/cry.jpg